@startuml

class Object {
    +hashCode() : int
    +equals(other : Object) : boolean
}

interface Comparable<T> {
    +compareTo(other : T) : int
}

interface Comparator<T> {
    +compare(x : T, y : T) : int
}

note "[x == y] : 0\n[x < y] : < 0\n[x > y] : > 0" as n1
Comparable .. n1
Comparator .. n1

@enduml
